[tools]
go = "latest"
usage = "latest"
maven = "latest"
java = "temurin-21"
python = "3.13"
neovim = "latest"
dust = "latest"
fzf = "latest"
lazygit = "latest"
eza = "latest"
yazi = "latest"
zellij = "latest"
uv = "latest"
sd = "latest"
duf = "latest"
delta = "latest"
node = "lts"
bun = "latest"
opencode = "latest"
gemini = "latest"
ast-grep = "latest"

[settings]
idiomatic_version_file_enable_tools = []
